const catalogItems = [
  {
    id: 'adobe-creative-cloud',
    title: 'Adobe Creative Cloud',
    category: 'Дизайн',
    description: 'Photoshop, Illustrator, Premiere Pro и весь пакет Adobe. Незаменимо для дизайнеров.',
    badges: ['Photoshop', 'Illustrator', 'Premiere'],
    tag: 'Хит',
    oldPrice: '20 000 ₽/год',
    price: '8 000 ₽/год',
    discount: '-60%',
    isFree: false,
    accent: 'orange',
  },
  {
    id: 'figma-education',
    title: 'Figma Education',
    category: 'Дизайн',
    description: 'Полная версия Figma с командными функциями — бесплатно для студентов.',
    badges: ['UI/UX', 'Прототипы', 'Командная работа'],
    tag: 'Бесплатно',
    oldPrice: '18 000 ₽/год',
    price: 'Бесплатно',
    discount: '',
    isFree: true,
    accent: 'magenta',
  },
  {
    id: 'jetbrains-all-products',
    title: 'JetBrains All Products',
    category: 'Разработка',
    description: 'IntelliJ IDEA, PyCharm, WebStorm, GoLand и все IDE JetBrains — бесплатно.',
    badges: ['IDE', 'Python', 'JavaScript'],
    tag: 'Бесплатно',
    oldPrice: '30 000 ₽/год',
    price: 'Бесплатно',
    discount: '',
    isFree: true,
    accent: 'blue',
  },
  {
    id: 'github-copilot',
    title: 'GitHub Copilot',
    category: 'Разработка',
    description: 'AI-помощник для написания кода от GitHub. Ускоряет разработку в 2-3 раза.',
    badges: ['AI-код', 'Автодополнение', 'Git'],
    tag: 'Бесплатно',
    oldPrice: '11 000 ₽/год',
    price: 'Бесплатно',
    discount: '',
    isFree: true,
    accent: 'violet',
  },
  {
    id: 'chatgpt-plus',
    title: 'ChatGPT Plus',
    category: 'AI-инструменты',
    description: 'GPT-4o, генерация изображений, анализ данных и плагины. Мощный AI-ассистент.',
    badges: ['GPT-4o', 'Изображения', 'Анализ'],
    tag: 'Хит',
    oldPrice: '2 000 ₽/мес',
    price: '1 000 ₽/мес',
    discount: '-50%',
    isFree: false,
    accent: 'teal',
  },
  {
    id: 'notion-education',
    title: 'Notion Education',
    category: 'Продуктивность',
    description: 'Заметки, базы данных, проектный менеджмент и wiki. Notion Plus бесплатно.',
    badges: ['Заметки', 'Проекты', 'База знаний'],
    tag: 'Бесплатно',
    oldPrice: '8 400 ₽/год',
    price: 'Бесплатно',
    discount: '',
    isFree: true,
    accent: 'slate',
  },
  {
    id: 'canva-pro',
    title: 'Canva Pro',
    category: 'Дизайн',
    description: 'Профессиональные шаблоны, фоны, элементы и функции удаления фона.',
    badges: ['Шаблоны', 'Брендинг', 'Презентации'],
    tag: 'Бесплатно',
    oldPrice: '7 200 ₽/год',
    price: 'Бесплатно',
    discount: '',
    isFree: true,
    accent: 'purple',
  },
  {
    id: 'microsoft-365',
    title: 'Microsoft 365 Education',
    category: 'Офис',
    description: 'Word, Excel, PowerPoint, Teams, OneDrive 1 ТБ — полный пакет Microsoft.',
    badges: ['Word', 'Excel', 'PowerPoint'],
    tag: 'Бесплатно',
    oldPrice: '5 000 ₽/год',
    price: 'Бесплатно',
    discount: '',
    isFree: true,
    accent: 'azure',
  },
  {
    id: 'autodesk-education',
    title: 'Autodesk Education',
    category: 'Дизайн',
    description: 'AutoCAD, 3ds Max, Maya, Revit — весь пакет Autodesk для студентов.',
    badges: ['CAD', '3D', 'Архитектура'],
    tag: 'Бесплатно',
    oldPrice: '160 000 ₽/год',
    price: 'Бесплатно',
    discount: '',
    isFree: true,
    accent: 'orange',
  },
]

export async function getCatalogItems() {
  await new Promise((resolve) => setTimeout(resolve, 120))
  return catalogItems
}
